### ISSUE TITLE
Serving up images in protected folder

### ISSUE THREAD

**Issue by dbd5** [mdmsoft/yii2-upload-file#7]
Hello,

Being that this folder '@common/upload' is not web accessible, how do you serve the images to the browser. What URL/anchors can be used?

Regards,

Adam

**Comment by mdmunir** [comment]
Using `FileController`
https://github.com/mdmsoft/yii2-upload-file#usage

**Comment by dbd5** [comment]
Thanks - works as expected!

Just one quick question, the URL to an image is of the form "domain.com/file?id=7"
Which means that a user can just change the value of id to see other pictures not belonging to them which is some what of a security concern, I also found that this URL works even when user has not logged on.

Please advise of how to prevent these situations:
When a user attempts to view an image not uploaded by the logged on user (Yii::$app->user->identity->id), I will like to throw a file not found error.

Regards,

Adam

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/yii-filters-accesscontrol.html
